services:
  - type: web
    name: motdar-elearning
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && pip install -r python_ai/requirements.txt && npm run build
    startCommand: node start_production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SMTP_USER
        value: soksithcheyhoout@gmail.com
      - key: SMTP_PASS
        value: hkxlhzduvlkgbeqg
